//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VansaetKendra_Gd1._1_DM_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guild
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guild()
        {
            this.Gebruikers = new HashSet<Gebruiker>();
        }
    
        public int GuildId { get; set; }
        public string Naam { get; set; }
        public System.DateTime DatumAangemaakt { get; set; }
        public string ServerNaam { get; set; }
        public string GuildType { get; set; }
        public string Partij { get; set; }
        public string Taal { get; set; }
        public string ItemLevel { get; set; }
        public string Regio { get; set; }
        public string LevelVereiste { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gebruiker> Gebruikers { get; set; }
    }
}
