//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VansaetKendra_Gd1._1_DM_Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Post()
        {
            this.Opmerkingen = new HashSet<Opmerking>();
        }
    
        public int PostId { get; set; }
        public string Titel { get; set; }
        public string Tekst { get; set; }
        public string Beschrijving { get; set; }
        public System.DateTime DatumGepost { get; set; }
        public int AuteurId { get; set; }
        public int GameVersieId { get; set; }
    
        public virtual GameVersie GameVersie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opmerking> Opmerkingen { get; set; }
    }
}
