//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VansaetKendra_Gd1._1_DM_Project_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WowheadEntities : DbContext
    {
        public WowheadEntities()
            : base("name=WowheadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievements { get; set; }
        public virtual DbSet<Categorie> Categories { get; set; }
        public virtual DbSet<GameVersie> GamesVersies { get; set; }
        public virtual DbSet<Gebruiker> Gebruikers { get; set; }
        public virtual DbSet<GebruikerAchievement> GebruikersAchievements { get; set; }
        public virtual DbSet<GebruikerReputatie> GebruikersReputaties { get; set; }
        public virtual DbSet<Guild> Guilds { get; set; }
        public virtual DbSet<Opmerking> Opmerkingen { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Reputatie> Reputaties { get; set; }
    }
}
