//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VansaetKendra_Gd1._1_DM_Project_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WowheadEntities : DbContext
    {
        public WowheadEntities()
            : base("name=WowheadEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievement { get; set; }
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<GameVersie> GameVersie { get; set; }
        public virtual DbSet<Gebruiker> Gebruiker { get; set; }
        public virtual DbSet<GebruikerAchievement> GebruikerAchievement { get; set; }
        public virtual DbSet<GebruikerReputatie> GebruikerReputatie { get; set; }
        public virtual DbSet<Guild> Guild { get; set; }
        public virtual DbSet<Opmerking> Opmerking { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Reputatie> Reputatie { get; set; }
    }
}
